/**
 * Responsive variants for local images under /images/{pois,tours,guides}.
 *
 * Convention (generated by scripts/generate-image-variants.mjs):
 *   /images/pois/x.webp  →  /images/pois/x_400.webp, x_800.webp, x_1600.webp
 * Variants are never upscaled but always exist for every base image.
 */
export const VARIANT_WIDTHS = [400, 800, 1600] as const
export type VariantWidth = (typeof VARIANT_WIDTHS)[number]

const IMG_EXT_RE = /\.(jpe?g|webp|png)$/i

export function imageVariantUrl(path: string, width: VariantWidth): string {
  return path.replace(IMG_EXT_RE, `_${width}.webp`)
}

/**
 * srcset string from pre-generated variants. Returns undefined (attribute
 * omitted, browser uses plain src) for empty/external/data URLs and for
 * paths outside the generated dirs — variants only exist there.
 */
export function imageSrcSet(
  path: string | null | undefined,
  widths: readonly VariantWidth[] = VARIANT_WIDTHS,
): string | undefined {
  if (!path) return undefined
  if (!/^\/images\/(pois|tours|guides)\//.test(path)) return undefined
  if (!IMG_EXT_RE.test(path)) return undefined
  return widths.map((w) => `${imageVariantUrl(path, w)} ${w}w`).join(', ')
}
